### ISSUE TITLE
How production-ready is turnpike?

### ISSUE THREAD

**Issue by elimisteve** [jcelliott/turnpike#111]
> Turnpike v2 is still under development, but is getting close to a stable release.
1. How stable is turnpike at present?
2. My team and I are considering just using the official JS Autobahn server since it's probably the best-supported implementation, even though we prefer Go on the backend.  Any idea how stable/production-ready that one is compared to turnpike?

Thanks!

**Comment by marshauf** [comment]
It is unstable. See issue #105 .
I don't recommend production use or starting development with this library unless you are willing to put time into it.

**Comment by elimisteve** [comment]
@marshauf Thanks!

**Comment by beatgammit** [comment]
Sorry for not getting back to you about this. We're using it in production, but our load is pretty light (just use it for a webapp). There are definitely bugs that need to be solved, but I may have time in the near future to dedicate to this.

You may be interested in the result of the discussion at #116.
