### ISSUE TITLE
Is it possible to block subscriptions from certain users?

### ISSUE THREAD

**Issue by jrudio** [jcelliott/turnpike#126]
Maybe I'm not understanding the concepts of realms and whether they are related to my question or not, but currently I have one realm for everything.
Say I want an admin user to listen for events on a protected channel: `admin_events`, but can't a user just subscribe to the same channel and they will receive the admin events?

**Comment by mourad** [comment]
Take a look at `authorizer.go`, you can provide your own implementation that authorizes (or not) a user to subscribe to your `admin_events` topic.

**Comment by jrudio** [comment]
Thank you, @mourad !

This is what I was looking for. I have a question that's more Go related, maybe you can help me out?

I can't seem to typecast on [the msg arg](https://github.com/jcelliott/turnpike/blob/v2/authorizer.go#L21).

When I do: 

``` go
if msg.MessageType() == "SUBSCRIBE" {
    sub := msg.(gowamp.Subscribe) // I get an error here
    topic := sub.Topic
}
```

The error message is: 

> impossible type assertion:
>   gowamp.Subscribe does not implement gowamp.Message (MessageType method has pointer receiver)

Ideally, I would check the topic against the `session.Id`

**Comment by jrudio** [comment]
Whoops, nevermind, I'm dumb. I needed the pointer(?) version: `*gowamp.Subscribe`.
