### ISSUE TITLE
Unnecessary dependency on Lumber?

### ISSUE THREAD

**Issue by maxekman** [jcelliott/turnpike#13]
First of all, this seems to be a nice library and I would love to (and will most likely) contribute when I start to use it soon!

Is the dependency on Lumber really necessary? As a networking library I think logging should be kept to a minimum and if anything be done with the built in logger. I would love to use Turnpike but I don't see a need for having Lumber forced on me (which will happen if I "go get" this at the moment.)

**Comment by jcelliott** [comment]
Glad you like turnpike. I agree about Lumber, I'll remove it.

**Comment by maxekman** [comment]
Perfect! Makes for a cleaner library without extra dependencies.
