### ISSUE TITLE
Status of turnpike?

### ISSUE THREAD

**Issue by dcelasun** [jcelliott/turnpike#130]
It seems like turnpike is semi-maintained by a few different people, but there are multiple open PRs and issues and it doesn't seem like there is any progress. Some of them look quite serious like [#94](https://github.com/jcelliott/turnpike/issues/94), [#85](https://github.com/jcelliott/turnpike/issues/85), [#50](https://github.com/jcelliott/turnpike/issues/50) and a few more.

Does any of the current maintainers plan to work on these?

**Comment by wstrm** [comment]
I know nothing about the current maintainers in this repo, but there has been active development in these:

https://github.com/awakenetworks/turnpike
https://github.com/beatgammit/turnpike

Would be really great if these two could go together and collaborate in a shared repository.

Maybe the current owner of this repo could arrange something?

**Comment by jcelliott** [comment]
I don't really have time to work on this right now. There are a few people besides me who have commit access, and they have been making some progress. @beatgammit and I were the original authors of the first implementation and the v2 rewrite, so if he plans on maintaining his fork I will link to that one as the "official" fork. I would like to hear his opinion as well as @mourad, @yanfali and any others who have been working on turnpike.

A shared repo would be another great option. I created a `go-turnpike` organization a long time ago (to resolve `gopkg.in/turnpike.v2` to turnpike v2) that I could turn over to current maintainers if anyone is interested.

**Comment by yanfali** [comment]
I'd love to see an org, and would be willing to participate. I am using turnpike at work daily and I really appreciate the solid work that has gone in to it.

One feature I would contribute, is an alternate backend implementation for Dealer. I'd also contribute some example code/documentation for simple authentication of wamp connections using ticket. I really like how flexible/pluggable the code base is.

**Comment by mourad** [comment]
I've contributed to the project a few times and continue to use turnpike daily as well, but have been more careful at making changes lately as I currently have 2 open PRs that I was hopeful that either @jcelliott or @beatgammit or others that know more about the direction that they would like to take turnpike could've provided feedback.

I am ok with whichever direction you decide to take, and am also willing to spend time should you decide to continue moving this repo forward.  I just did not want to introduce changes that negatively affected others simply because no one was available to review them.

**Comment by mourad** [comment]
I've gone ahead and added my changes to the v2 branch, as I've been working with them for quite a while and haven't seen any significant issues.

I plan on continuing to work on turnpike as time permits, and fix issues as I find them.

**Comment by migueleliasweb** [comment]
+1 as a wish for this repo come back to life !

**Comment by beatgammit** [comment]
Me too 😞 

I use it in production, and it's reasonably stable, but there are still occasional crashes from runtime panics. I have a branch that fixes a few of them, so I just need to sit down and rethink the concurrency model to make sure I'm happy before merging.

**Comment by richardartoul** [comment]
About to start using this in production and wondering if there is any status update? @beatgammit What kind of load are you handling in production?

**Comment by beatgammit** [comment]
@richardartoul Not too much, something like 5 clients and tens of messages per second. My fork has some concurrency fixes (to fix panics, though they probably don't scale well), so feel free to take a look at that if you like.
