### ISSUE TITLE
Add WAMP-CRA authentication and permissions

### ISSUE THREAD

**Issue by maxekman** [jcelliott/turnpike#15]
I will probably take a go at this soon, just wanted it noted here.

Some references:
https://github.com/tavendo/AutobahnPython/tree/master/examples/wamp/authentication
http://cljwamp.us/tutorial#wampcra

**Comment by jcelliott** [comment]
Closing WAMPv1 issues. See WAMPv2 development on [v2 branch](https://github.com/jcelliott/turnpike/tree/v2).

Started work on WAMP Authentication in 66e8638f
