### ISSUE TITLE
Implement Client

### ISSUE THREAD

**Issue by beatgammit** [jcelliott/turnpike#2]

**Comment by maxekman** [comment]
I have written the event handler for the client and will create a pull request as soon as the pull request adding licenses is merged in (https://github.com/jcelliott/turnpike/pull/22). I'm a bit unsure about what to base my topic branches on when I change a lot of code. Hope I'm not causing too much pain...

You can preview the code (minus license header changes) here: https://github.com/maxpersson/turnpike/compare/jcelliott:dev...mp-client_event_handler

**Comment by jcelliott** [comment]
Closing WAMPv1 issues. See WAMPv2 development on [v2 branch](https://github.com/jcelliott/turnpike/tree/v2).
