### ISSUE TITLE
Review WAMPv2 basic API

### ISSUE THREAD

**Issue by beatgammit** [jcelliott/turnpike#39]
This is a meta-issue for things that should be considered before releasing `turnpike` as a WAMPv2 implementation:
- [x] change Serializer interface to support streaming
- [x] review messages and message types (custom message types?)
- [x] should JSON/MessagePack be supported, or should users be required to register them (i.e. if they didn't want to support one of the protocols for some reason)
- [x] should `turnpike` be broken up into smaller packages?

**Comment by jcelliott** [comment]
Also, make sure the current implementation is flexible enough to easily add advanced profile features.

**Comment by beatgammit** [comment]
Should `JoinRealmAuth` be `JoinRealmCRA` instead? There may be other authentication modes than challenge/response authentication in the future.

**Comment by jcelliott** [comment]
Changed to JoinRealmCRA.
