### ISSUE TITLE
Add 'omitempty' to args and kwargs

### ISSUE THREAD

**Issue by jcelliott** [jcelliott/turnpike#44]
https://github.com/tavendo/WAMP/blob/master/spec/basic.md#empty-arguments-and-keyword-arguments

**Comment by beatgammit** [comment]
Perhaps optional fields can have a `wamp` tag:

```
type Call struct {
    Request ID
    Options map[string]interface{}
    Procedure URI
    Arguments []interface{} `wamp:"omitempty"`
    ArgumentsKw map[string]interface{} `wamp:"omitempty"`
}
```

Fields will be traversed backwards looking for `omitempty`, and those that are `nil` or 0-length are omitted.
