### ISSUE TITLE
Implement RPC functions for client

### ISSUE THREAD

**Issue by jcelliott** [jcelliott/turnpike#48]

**Comment by josephschorr** [comment]
Hey guys,

Any status update on this feature? If no, are there any requirements/restrictions if I decide to implement the basics of RPC (REGISTER and CALL)?

**Comment by jcelliott** [comment]
I was planning on getting to it later this week. Glad to have other people help though, so If you do want to work on it let me know. The only requirements are to use `gofmt` and to have a basic test for it.

**Comment by josephschorr** [comment]
I'm planning to work on it on Friday, so let me know if you get around to it before then. If not, I'll take a stab then.

**Comment by josephschorr** [comment]
@jcelliott: I just saw this fork when starting my own: https://github.com/AnimationMentor/turnpike/blob/wamp-2/client.go

Is there a reason it isn't merged in?

**Comment by jcelliott** [comment]
The code that link points to is part of Turnpike v1, targeting WAMP v1. I'm not sure why it's on the wamp-2 branch in that fork. This issue is specifically for adding this functionality for WAMP v2. Which version of WAMP are you using?

**Comment by josephschorr** [comment]
I'm planning to use WAMP v2. As you point out, despite its name, it does appear to be a fork of the WAMP v1 client, so I'll continue with my plans to fork the v2 and add RPC there.

**Comment by jcelliott** [comment]
Started in bfca50332d6dd5524ff6c1cde8545e3824ad6fcd

**Comment by josephschorr** [comment]
Continued in https://github.com/jcelliott/turnpike/commit/6ad6cd9b79ae8c28fdbfa27c4ad4b705851f347b

**Comment by josephschorr** [comment]
Anything else you'd like me to add for this issue?

**Comment by jcelliott** [comment]
Nope, it looks good. I'm doing some refactoring as part of implementing client side auth, and I'll close this issue after that's complete.

**Comment by jcelliott** [comment]
@josephschorr Let me know if the changes I made will not work for your use case.
