### ISSUE TITLE
Binary in JSON strings

### ISSUE THREAD

**Issue by beatgammit** [jcelliott/turnpike#49]
https://github.com/tavendo/WAMP/blob/rc3/spec/basic.md#binary-conversion-of-json-strings

Basically we'll need to introduce a binary type that implements MarshalJSON that prefixes the string with `\x00`. `encoding/json` already base64-encodes binary strings, so perhaps that can be reused.

**Comment by beatgammit** [comment]
I'm mostly done with this. Here's the current gameplan:
- make a `type Binary []byte` that marshals/unmarshals properly (done, just needs to be cleaned up)
- replace `[]byte` with above in the JSON serializers before handing it to `encoding/json`

I'm not so sure about part 2 because it seems like a lot of overhead. However, requiring all users to `s/[]byte/turnpike.Binary/g` seems nasty as well. Maybe I'll write the function, but not use it so users can choose what to do (perhaps this will be an option on the serializer).

I'm sure there are other formats where there is no distinction between `[]byte` and `string`, so perhaps this is the best way.

**Comment by beatgammit** [comment]
@jcelliott - Should this be left open until the magic function is written, or do you think #56 is good enough to satisfy the requirement. It puts the burden on the user, but at least it's possible.

I got partway through writing the magic function, but it ended up being more complex than I had initially thought. For example, these cases:
- map with byte array key: `map[[5]byte]interface{}`
- struct implements MarshalJSON and includes a `[]byte`
  - we could special case it, but we don't currently support `UnmarshalJSON`

If we don't do the magic function, we can simplify the unmarshalling by using `json.RawMessage` instead of doing a bunch of reflection. This would probably net us some performance gains since `encoding/json` is likely more optimized than our hacked-together solution.

**Comment by jcelliott** [comment]
I think this is good enough for now. Most people will not be using binary data with JSON (they would be more likely to use msgpack), but if they need to it's possible.
