### ISSUE TITLE
Publish hook

### ISSUE THREAD

**Issue by beatgammit** [jcelliott/turnpike#5]
Something like this should work:

```
type EventListener func (string, interface{})
RegisterEventListener(topicURI string, fun EventListener)
```

If topicURI is the empty string, the listener will be called on every PUBLISH.

**Comment by jcelliott** [comment]
Closing WAMPv1 issues. See WAMPv2 development on [v2 branch](https://github.com/jcelliott/turnpike/tree/v2).
