### ISSUE TITLE
Not compatible with autobahn.js on GOODBAY.

### ISSUE THREAD

**Issue by tomwys** [jcelliott/turnpike#60]
Autobahn expects that `details` in `GOODBAY` should be set to dictionary/map. turnpike sets this parameter to `nil`.

Fix should look something like that:

```
./router.go:            sess.Send(&Goodbye{Reason: reason, Details: make(map[string]interface{})})

./router.go:            sess.Send(&Goodbye{Reason: WAMP_ERROR_GOODBYE_AND_OUT, Details: make(map[string]interface{})})
```

PS. I'm not 100% sure that this is turnpike fault, but after reading WAMP documentation it seams to me that Autobahn implementation is good and turnpike should be fixed. If you thing differently please create ticket to Autobahn.

**Comment by jcelliott** [comment]
Good catch, thanks.
