### ISSUE TITLE
Refering to "github.com/jcelliott/turnpike" in "examples/chat/chatserver/main.go" breaks "go get -u all"

### ISSUE THREAD

**Issue by quietnan** [jcelliott/turnpike#62]
How to reproduce:

Create clean $GOPATH:

> mkdir $HOME/tempgo
> export GOPATH=$HOME/tempgo

install turnpike.v2:

> go get gopkg.in/jcelliott/turnpike.v2

break it by updating:

> go get -u all

attempts to get "github.com/jcelliott/turnpike" (master branch) and its various dependencies (github.com/nu7hatch/gouuid and others), that are not needed for v2

The chatserver example should probably refer to the gopkg.in path?

**Comment by beatgammit** [comment]
Good catch! That could have caused interesting errors for someone trying to run that example.
