### ISSUE TITLE
Add basic API documentation

### ISSUE THREAD

**Issue by jcelliott** [jcelliott/turnpike#66]

**Comment by jcelliott** [comment]
- [x] add a list of things that need to be documented

**Comment by beatgammit** [comment]
Undocumented things:
- [x] callresult.go - I thought we should review these before documenting
  - [x] ValueResult
  - [x] SliceResult
  - [x] MapResult
  - [x] SimpleErrorMessage
  - [x] ErrorResult
- [x] Message types

**Comment by beatgammit** [comment]
We decided to remove the convenience functions in callresult.go because they really didn't add much. Also, since the members were private, they could not be serialized.

I've made the members public, so these convenience functions can be added in a utility library.

**Comment by beatgammit** [comment]
Documentation for the message types is good enough for an initial release, but additional documentation is definitely welcome.
