### ISSUE TITLE
Origin not allowed

### ISSUE THREAD

**Issue by kacpersaw** [jcelliott/turnpike#73]
Hi,
In title I made mistake. Instead of now should be not.
I created two servers. First server is turnpike.v2 server, second server is client(autobahn) in JS.
When i try to connect i got: `Error during WebSocket handshake: Unexpected response code: 403` and in terminal: 

``` bash
websocket_server.go:103: WebsocketServer.ServeHTTP GET /ws
websocket_server.go:107: Error upgrading to websocket connection: websocket: origin not allowed
```

**Comment by beatgammit** [comment]
I fixed the title for you.

It looks like our web example is broken as well (see #74), but with the patch it works just fine. The example uses the latest autobahn.js from the CDN.

Are you using the latest turnpike (`go get -u gopkg.in/jcelliott/turnpike.v2`)? Do you have some code to reproduce this?

**Comment by kacpersaw** [comment]
Thanks for title change :)
Yes, I'm using the latest version of turnpike.
Okay, I have code to reproduce this.
server.go

``` go
package main

import (
    "gopkg.in/jcelliott/turnpike.v2"
    "log"
    "net/http"
)

func main() {
    turnpike.Debug()
    s := turnpike.NewBasicWebsocketServer("realm") 
        //http.Handle("/", http.FileServer(http.Dir(".")))
    http.Handle("/ws", s)
    log.Fatal(http.ListenAndServe(":9000", nil))
}
```

client.go

``` go
package main

import (
    "log"
    "net/http"
)

func main() {
    http.Handle("/", http.FileServer(http.Dir(".")))
    log.Fatal(http.ListenAndServe(":9001", nil)) 
}
```

index.html

``` html
<html>
<head>
    <title>Client</title>
    <script src="https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            var conn = new autobahn.Connection({
                url: 'ws://localhost:9000/ws',
                realm: 'realm',
            });

            conn.onopen = function(sess) {
            };

            conn.open();
        });
    </script>
</head>
<body></body>
</html>
```

If you run index.html on server where turnpike is, client works.

**Comment by beatgammit** [comment]
I'll take a look at this later today hopefully Thanks!

**Comment by marshauf** [comment]
Check if your request.Header["Origin"] is nil or of the length 0.
If I connect with a browser using a js file. Firefox sets the Origin header to "null". Which results in request.Header["Origin"] = []string{"null"} which does not pass the default checkSameOrigin function of gorilla websocket.

My guess is that in your case you send a request from "localhost:9000" to "localhost:9001" with the Origin set to "localhost:9000" which doesn't pass the default checkSameOrigin function.

My workaround:

``` Go
http.HandleFunc("/ws", func(w http.ResponseWriter, req *http.Request) {
    req.Header["Origin"] = nil
    s.ServeHTTP(w, req)
})
```

**Comment by mattbaird** [comment]
hey @beatgammit , I think the solution is to pass the CheckOrigin func to the upgrader:

```
s.Upgrader = &websocket.Upgrader{CheckOrigin: func(r *http.Request) bool {
    return allowDifferentOrigin
}}
```

I patched websocket_server.go to take allDifferentOrigin which is a quick and dirty hack, but allowed multiple origins (ports) to work just fine.

What really needs to happen is a bigger change to being able to optionally pass in some configuration,  however either we use the named parameters and lose the ability to execute the constructor or we change the constructor signatures. Maybe we could introduce a new constructor.

I don't mind writing the software, do you have a preference on the approach?

**Comment by mattbaird** [comment]
pinging @beatgammit

**Comment by beatgammit** [comment]
Thanks for bringing this back up! I don't know if anyone actually uses the origin check since it's a pretty awful security feature (just blocks web pages) and is mostly just annoying, but we should probably be up to spec where possible.

@jcelliott - Do you have any thoughts about this?

I'll look into this sometime over the next few days (and feel free to ping me again if I go AWOL again) and if @jcelliott doesn't answer by then, I'll make an executive decision.

**Comment by mattbaird** [comment]
@beatgammit thanks. It turns out to be a fairly important enhancement as the new turnpike can't pass a handle to a container like revel, so you need to run your websockets on a different port.

**Comment by jcelliott** [comment]
It looks like the `Upgrader` field on `WebsocketServer` is already exposed (from [this PR](https://github.com/jcelliott/turnpike/pull/82)), so couldn't you just do:

``` go
s := turnpike.NewBasicWebsocketServer("realm")
allowAllOrigin := func(r *http.Request) bool { return true }
s.Upgrader.CheckOrigin = allowAllOrigin
```

**Comment by mattbaird** [comment]
@jcelliott Yep - this worked. Didn't notice the function was exposed. This worked, thank you!

**Comment by gsaqui** [comment]
@jcelliott can I suggest you put the following somewhere on the wiki?
```
s := turnpike.NewBasicWebsocketServer("realm")
allowAllOrigin := func(r *http.Request) bool { return true }
s.Upgrader.CheckOrigin = allowAllOrigin
```
