### ISSUE TITLE
Stop clients from registering RPC functions

### ISSUE THREAD

**Issue by marshauf** [jcelliott/turnpike#77]
Hello,

I want to stop clients(browser) from registering RPC functions. If I understand the concept of WAMP correctly I can implement this by:
Challenging the client to authenticate itself. The client authenticates itself with roles.
The (custom)Dealer checks if the client (session?) is authenticated with a rule which allows RPC registration. If authenticated and correct rule, the client can register a RPC function.

If my assumption is correct, how do I get the SessionID as a Dealer? Do I need to send the SessionID via the Options of the Register message?

Thanks in advance.

**Comment by jcelliott** [comment]
This is discussed in #80. If that doesn't solve the issue you can re-open this one.
