### ISSUE TITLE
Test with Autobahn test suite

### ISSUE THREAD

**Issue by jcelliott** [jcelliott/turnpike#9]
This is blocked by a bug in the go websocket library

**Comment by maxekman** [comment]
This should probably be done at for example [drone.io](drone.io) to keep the code base clean.

**Comment by jcelliott** [comment]
No longer blocked since we're using Gorilla websockets.

**Comment by jcelliott** [comment]
Autobahn doesn't provide a WAMP test suite anymore (not sure they ever did). We do have an example that uses Autobahn|Python.
