### ISSUE TITLE
Register callees and publishers on router

### ISSUE THREAD

**Issue by theduke** [jcelliott/turnpike#99]
I've scanned through the code, but have not found a way to do it.

I want to use WAMP as the protocol just between a Javascript client and my application server.
The go server will be the router and also serve as callee and publisher.

So I would like to publish events directly on the router, and also to have functions serve as callees directly on the router without a redundant network rountrip.

Is this implemented?

**Comment by theduke** [comment]
Whoops.
"GetLocalClient()".

Never mind.

**Comment by jcelliott** [comment]
> "GetLocalClient()".

Yep. Feel free to open another issue if you come across improvements that can be made to that process.
